filter:
    excluded_paths: [app/config,app/config/*]

tools:
    php_cpd:
        enabled: true
        excluded_dirs: [app/config,app/config/*]
    php_cs_fixer:
        enabled: true
        filter:
            excluded_paths: [app/config,app/config/*]
    php_loc:
        enabled: true
    php_mess_detector:
        enabled: true
        config:
            rulesets: [phpmd.xml]
    php_pdepend:
        enabled: true
        excluded_dirs: [app/config,app/config/*]
    php_analyzer:
        enabled: true
        filter:
            excluded_paths: [app/config,app/config/*]
        config:
            checkstyle:
                enabled: true
            verify_php_doc_comments:
                enabled: true
            doc_comment_fixes:
                enabled: true
            use_statement_fixes:
                enabled: true
                remove_unused: true
                preserve_multiple: false
                order_alphabetically: true
    sensiolabs_security_checker:
        enabled: true
