filter:
    excluded_paths: [app/config,app/config/*,app/database,app/database/*,app/libraries,app/libraries/*,app/storage,app/storage/*]

tools:
    php_mess_detector:
        enabled: true
        config:
            rulesets: [phpmd.xml]
    php_cpd:
        enabled: true
        excluded_dirs: [app/config,app/config/*,app/database,app/database/*,app/libraries,app/libraries/*,app/storage,app/storage/*]
    php_pdepend:
        enabled: true
        excluded_dirs: [app/config,app/config/*,app/database,app/database/*,app/libraries,app/libraries/*,app/storage,app/storage/*]
